// Generated by Xata Codegen 0.18.0. Please do not edit.
import { buildClient } from '@xata.io/client'
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: 'products',
    columns: [
      { name: 'name', type: 'string' },
      { name: 'description', type: 'text' },
      { name: 'price', type: 'float' },
      { name: 'stock', type: 'int' },
      { name: 'thumbnail', type: 'string' },
      { name: 'media', type: 'multiple' },
    ],
  },
]
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient()
const defaultOptions = {
  databaseURL: process.env.DATABASE_URL,
}
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables)
  }
}
let instance = undefined
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance
  instance = new XataClient()
  return instance
}
